Bán Mỹ Phẩm/Controllers/DanhMucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bán_Mỹ_Phẩm.Models;
using System.Net;

namespace Bán_Mỹ_Phẩm.Controllers
{
    public class DanhMucController : Controller
    {
        //
        // GET: /ThuongHieuPartial/
        QL_MyPham_DAEntities3 db = new QL_MyPham_DAEntities3();

        public ActionResult ThuongHieuPartial()
        {
            var ListTH = db.ThuongHieux.OrderBy(th => th.TenTH).ToList();
            return PartialView(ListTH);
        }


        public ViewResult SanPhamTheoTH(string maTH)
        {
            var ListTH = db.SanPhams.Where(s => s.MaTH == maTH).OrderBy(s => s.GiaBan).ToList();
            if (ListTH.Count == 0)
            {
                ViewBag.Imagename = "/Images/erro.png";            
                ViewBag.SanPham = "Không có sản phẩm nào thuộc thương hiệu này";
            }
            return View(ListTH);
        }

        public ActionResult xemchitiet(string Masp = "")
        {
            var chitiet = db.SanPhams.SingleOrDefault(n => n.MaSP == Masp);
            if (chitiet == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(chitiet);
        }     

    }
}

Bán Mỹ Phẩm/Views/DanhMuc/ThuongHieuPartial.cshtml
@using Bán_Mỹ_Phẩm.Models;
@model List<ThuongHieu>


@{
    ViewBag.Title = "MPV - Danh Mục";
}

<div>
    <h3 style="padding-left:20px" class="h3">Thương Hiệu</h3>
    @{
        foreach (var item in Model)
        {
            <button type="button" class="btn btn-primary">
                <a href="@Url.Action("SanPhamTheoTH", "DanhMuc", new { @maTH = item.MaTH })">@item.TenTH</a>
            </button>
        }
    }
</div>
<br />
<style>
    a {
        text-decoration: none;
        color: white;
    }

        a:hover {
            text-decoration: none;
            color: white;
        }

    .h3 {
        color: #ff6a13;
        font-size: 23px;
        font-weight: 700;
        display: inline-block;
        background: #fff;
        width: 100%;
        padding: 19px 5px;
        line-height: 1.4;
    }
</style>

Bán Mỹ Phẩm/Views/DanhMuc/xemchitiet.cshtml
@using Bán_Mỹ_Phẩm.Models
@model SanPham

@{
    ViewBag.Title = "MPV - " + @Model.TenSP;
}

<style>
    .main-product {
        width: 100%;
        height: 652px;
        position: relative;
        background: white;
    }

        .main-product .product-item {
            padding: 68px 0 0;
        }

    .container {
        max-width: 1200px;
        width: 100%;
        margin: 0 auto;
        padding: 0 10px;
        position: relative;
    }

    .main-product .product-item .wrap .copy h3 {
        font-family: "Montserrat", sans-serif;
        font-size: 3rem;
        font-weight: 700;
        margin-bottom: 2.6rem;
    }

    .main-product .product-item .wrap .img {
        max-width: 460px;
    }

        .main-product .product-item .wrap .img .item {
            background: white;
            width: 100%;
            height: 0;
            padding-bottom: 100%;
            float: left;
            border-left: 1px solid #f0f0f0;
            position: relative;
            box-shadow: 0px 0px 30px -10px rgba(0, 0, 0, 0.5);
        }

    .main-product .product-item .wrap:first-child {
        width: 45%;
    }

    .main-product .product-item .wrap:last-child {
        width: 55%;
        padding-top: 30px;
    }

    .main-product .product-item .wrap {
        width: 50%;
        float: left;
        padding: 0 1rem;
    }

    strong {
        display: block;
        color: #e2252d;
        font-size: 24px;
    }

    em {
        font-style: normal;
        text-decoration-line: line-through;
    }

    i {
        font-style: normal;
    }

    img {
        border: 0;
        vertical-align: middle;
    }

    .short-article__title {
        display: block;
        overflow: hidden;
        font-size: 20px;
        color: #000;
        font-weight: 600;
        padding: 5px 0;
        margin-bottom: 10px;
    }

    button.btn-cart:hover {
        background: #000;
        color: #fff;
    }

    button.btn-cart {
        border-width: 1px;
        border-color: #ccc;
        max-width: 228px;
        width: 100%;
        display: block;
        padding: 2px 10px 2px;
        border: 2px solid #000;
        background: transparent;
        font-size: 16px;
        text-transform: uppercase;
        color: #000;
        line-height: 40px;
        text-align: center;
        border-radius: 0;
        letter-spacing: 1px;
    }
</style>

<br />
<div class="main-product">
    <div class="container">
        <article class="product-item">
            <div class="wrap">
                <div class="img">
                    <div class="item">
                        <article>
                            <figure>
                                <img src=@Url.Content("~/Images/"+ @Model.HinhAnh) class="img-responsive" alt="" width="460" height="460" />
                            </figure>
                        </article>
                    </div>
                </div>
            </div>
            <div class="wrap">
                <div class="copy">
                    <h3>@Model.TenSP</h3>
                    <div style="font-weight: 400; font-size: 14px; color: rgb(32, 32, 32); margin-bottom: 10px;">Thương hiệu:<span style="font-weight: 300; font-size: 14px; color: #fe2c6d; padding: 0px 4px; ">@Model.ThuongHieu.TenTH</span></div>
                    <div style="font-weight: 400; font-size: 14px; color: rgb(32, 32, 32); margin-bottom: 10px;">Loại sản phẩm:<span style="font-weight: 300; font-size: 14px; color: #fe2c6d; padding: 0px 4px;">@Model.LoaiHang.TenLoai</span></div>
                    <div style="font-weight: 400; font-size: 14px; color: rgb(32, 32, 32); margin-bottom: 10px;">HSD:<span style="font-weight: 300; font-size: 14px; color: #fe2c6d; padding: 0px 4px;">@Model.HSD</span></div>
                    <br />
                    <strong>@String.Format("{0:0,0}", @Model.iKHuyenMai()) VNĐ</strong>
                    <em>@String.Format("{0:0,0}", @Model.GiaBan) VNĐ</em>
                    <i>(-@Model.KhuyenMai.TenKM%)</i>
                    <p class="short-article__title">Mô tả</p>
                    <ul>
                        <li>@Model.MoTa</li>
                    </ul>
                    <br />
                    <div class="product-price-btn">
                        @using (Html.BeginForm("ThemGioHang", "GioHang", new { @iMasp = @Model.MaSP, @strURL = Request.Url.ToString() }))
                        {
                            <button class="btn-cart">
                                Thêm vào giỏ
                            </button>
                        }
                    </div>
                </div>
            </div>
        </article>
    </div>
</div>
<br />